const D=window.FREIGHT_DATA;
const $=s=>document.querySelector(s);
const fmt={num:n=>Math.round(n).toLocaleString(),pct:n=>(n*100).toFixed(1)+'%',money:n=>'$'+(Math.abs(n)>=1e6?(n/1e6).toFixed(2)+'M':(n/1e3).toFixed(0)+'K')};
const colors=['#27c5a1','#f0aa43','#ef7f70','#7258e8'];

function fillSelect(id,values){const el=$(id);el.innerHTML='<option value="All">All</option>'+values.map(v=>`<option>${v}</option>`).join('')}
fillSelect('#month',[...new Set(D.cube.map(x=>x.month))]);fillSelect('#region',[...new Set(D.cube.map(x=>x.region))].sort());fillSelect('#mode',[...new Set(D.cube.map(x=>x.mode))].sort());

function filtered(){const m=$('#month').value,r=$('#region').value,t=$('#mode').value;return D.cube.filter(x=>(m==='All'||x.month===m)&&(r==='All'||x.region===r)&&(t==='All'||x.mode===t))}
function aggregate(rows){const n=rows.reduce((a,x)=>a+x.shipments,0)||1;return {shipments:rows.reduce((a,x)=>a+x.shipments,0),otif:rows.reduce((a,x)=>a+x.otif*x.shipments,0)/n,onTime:rows.reduce((a,x)=>a+x.onTime*x.shipments,0)/n,exceptions:rows.reduce((a,x)=>a+x.exceptions*x.shipments,0)/n,cost:rows.reduce((a,x)=>a+x.cost,0),variance:rows.reduce((a,x)=>a+x.variance,0)}}
function update(){const rows=filtered(),a=aggregate(rows);$('#kShip').textContent=fmt.num(a.shipments);$('#kOtif').textContent=fmt.pct(a.otif);$('#kTime').textContent=fmt.pct(a.onTime);$('#kException').textContent=fmt.pct(a.exceptions);$('#kCost').textContent=fmt.money(a.cost);$('#kVariance').textContent=fmt.money(a.variance);renderTrend(rows)}

function renderTrend(rows){const by={};rows.forEach(x=>{by[x.month]??={n:0,v:0};by[x.month].n+=x.shipments;by[x.month].v+=x.otif*x.shipments});const pts=Object.entries(by).sort().map(([m,x])=>({m,v:x.v/x.n}));const el=$('#trendChart');if(!pts.length){el.innerHTML='<div class="empty">No data</div>';return}const W=760,H=270,p={l:44,r:18,t:18,b:38};let min=Math.min(...pts.map(x=>x.v))-.02,max=Math.max(...pts.map(x=>x.v))+.02;const x=i=>p.l+i*(W-p.l-p.r)/Math.max(1,pts.length-1),y=v=>p.t+(max-v)*(H-p.t-p.b)/(max-min);const path=pts.map((d,i)=>(i?'L':'M')+x(i)+','+y(d.v)).join(' ');const area=path+` L${x(pts.length-1)},${H-p.b} L${x(0)},${H-p.b} Z`;let grid='';for(let i=0;i<4;i++){const yy=p.t+i*(H-p.t-p.b)/3,val=max-i*(max-min)/3;grid+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#eceef4"/><text x="4" y="${yy+4}" fill="#999cad" font-size="10">${(val*100).toFixed(0)}%</text>`}const labels=pts.map((d,i)=>i%Math.ceil(pts.length/6)===0?`<text x="${x(i)}" y="${H-10}" text-anchor="middle" fill="#999cad" font-size="9">${d.m.slice(2)}</text>`:'').join('');const dots=pts.map((d,i)=>`<circle cx="${x(i)}" cy="${y(d.v)}" r="4" fill="#fff" stroke="#7357e8" stroke-width="2"><title>${d.m}: ${fmt.pct(d.v)}</title></circle>`).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7357e8" stop-opacity=".25"/><stop offset="1" stop-color="#7357e8" stop-opacity="0"/></linearGradient></defs>${grid}<path d="${area}" fill="url(#area)"/><path d="${path}" fill="none" stroke="#7357e8" stroke-width="3" vector-effect="non-scaling-stroke"/>${dots}${labels}</svg>`}

function bars(el,data,label,value,format,colorClass=''){const max=Math.max(...data.map(value));$(el).innerHTML=data.map((d,i)=>`<div class="bar-row"><label title="${label(d)}">${label(d)}</label><div class="bar-track"><div class="bar-fill" style="width:${value(d)/max*100}%;animation-delay:${i*.05}s"></div></div><b>${format(value(d))}</b></div>`).join('')}
bars('#carrierChart',D.carriers.slice(0,7),d=>d.carrier_name,d=>d.otif_rate,fmt.pct);
bars('#exceptionChart',D.exceptions.slice().sort((a,b)=>b.shipments-a.shipments).slice(0,7),d=>d.exception_code,d=>d.shipments,fmt.num);

function donut(){const total=D.riskBands.reduce((a,x)=>a+x.value,0);let acc=0;const stops=D.riskBands.map((x,i)=>{const start=acc/total*100;acc+=x.value;return `${colors[i]} ${start}% ${acc/total*100}%`}).join(',');$('#riskDonut').style.background=`conic-gradient(${stops})`;$('#riskLegend').innerHTML=D.riskBands.map((x,i)=>`<div class="risk-item"><span><i style="background:${colors[i]}"></i>${x.name}</span><b>${fmt.num(x.value)}</b></div>`).join('')}
donut();

function facilities(){const data=D.facilities,W=760,H=260,p={l:55,r:25,t:20,b:40},minX=Math.min(...data.map(d=>d.otif))-.01,maxX=Math.max(...data.map(d=>d.otif))+.01,minY=Math.min(...data.map(d=>d.variance)),maxY=Math.max(...data.map(d=>d.variance));const x=v=>p.l+(v-minX)/(maxX-minX)*(W-p.l-p.r),y=v=>H-p.b-(v-minY)/(maxY-minY)*(H-p.t-p.b);const maxN=Math.max(...data.map(d=>d.shipments));let grid='';for(let i=0;i<4;i++){const yy=p.t+i*(H-p.t-p.b)/3;grid+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#eceef4"/>`}const bubbles=data.map((d,i)=>`<circle class="bubble" cx="${x(d.otif)}" cy="${y(d.variance)}" r="${9+18*Math.sqrt(d.shipments/maxN)}" fill="${colors[i%4]}" fill-opacity=".72" stroke="white" stroke-width="2" data-tip="${d.facility_name}|${fmt.pct(d.otif)} OTIF · ${fmt.money(d.variance)} variance"><title>${d.facility_name}</title></circle>`).join('');$('#facilityChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}<text x="8" y="18" fill="#999cad" font-size="10">COST ↑</text><text x="${W-80}" y="${H-8}" fill="#999cad" font-size="10">OTIF →</text>${bubbles}</svg>`;document.querySelectorAll('.bubble').forEach(b=>{b.addEventListener('mousemove',e=>showTip(e,b.dataset.tip));b.addEventListener('mouseleave',hideTip)})}
facilities();

$('#laneList').innerHTML=D.lanes.slice(0,5).map((d,i)=>`<div class="lane"><span class="rank">0${i+1}</span><div><strong>${d.origin} → ${d.facility_name.replace(' DC','')}</strong><small>${fmt.num(d.shipments)} loads · ${fmt.money(d.cost_variance)} variance</small></div><div class="lane-score"><b>${fmt.pct(d.otif_rate)}</b><small>OTIF</small></div></div>`).join('');
const tip=document.createElement('div');tip.className='tooltip';document.body.appendChild(tip);function showTip(e,t){const [a,b]=t.split('|');tip.innerHTML=`<b>${a}</b><br>${b}`;tip.style.left=e.clientX+12+'px';tip.style.top=e.clientY+12+'px';tip.style.opacity=1}function hideTip(){tip.style.opacity=0}
['#month','#region','#mode'].forEach(id=>$(id).addEventListener('change',update));$('#reset').addEventListener('click',()=>{['#month','#region','#mode'].forEach(id=>$(id).value='All');update()});
document.querySelectorAll('.nav').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
update();
